import React, { useState, useEffect } from 'react';
import { Timeframe, Region } from '../types';
import { generateExecutiveSummary } from '../mockData';
import { Sparkles, RefreshCw, Calendar, FileText } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';

interface NarrativeEngineProps {
  region: Region;
  timeframe: Timeframe;
  onTimeframeChange: (timeframe: Timeframe) => void;
  highRiskCount: number;
  quarantinedCount: number;
}

export const NarrativeEngine: React.FC<NarrativeEngineProps> = ({
  region,
  timeframe,
  onTimeframeChange,
  highRiskCount,
  quarantinedCount,
}) => {
  const [isGenerating, setIsGenerating] = useState(false);
  const [displayedText, setDisplayedText] = useState('');

  const rawSummaryText = generateExecutiveSummary(timeframe, region, highRiskCount, quarantinedCount);

  // Simulate text generation/typing effect on change
  useEffect(() => {
    setIsGenerating(true);
    setDisplayedText('');
    const timer = setTimeout(() => {
      setIsGenerating(false);
      setDisplayedText(rawSummaryText);
    }, 400);

    return () => clearTimeout(timer);
  }, [timeframe, region, highRiskCount, quarantinedCount]);

  return (
    <div className="bg-slate-800/80 border border-slate-700/60 rounded-xl p-5 shadow-lg flex flex-col justify-between h-full" id="narrative-engine">
      <div>
        {/* Title Section */}
        <div className="flex justify-between items-start mb-4">
          <div>
            <h2 className="text-sm font-bold text-white tracking-wide uppercase flex items-center gap-2">
              <Sparkles className="w-4 h-4 text-emerald-400" />
              Executive Narrative Engine
            </h2>
            <p className="text-xs text-slate-400 mt-1">
              Dynamic legal summaries generated by Bastion Audit Oversight LLM
            </p>
          </div>
        </div>

        {/* Timeframe selector tabs */}
        <div className="flex items-center justify-between bg-slate-950 p-1.5 rounded-lg border border-slate-800 mb-4">
          <span className="text-[10px] font-mono text-slate-500 uppercase pl-1.5 flex items-center gap-1">
            <Calendar className="w-3 h-3" /> Timeframe
          </span>
          <div className="flex gap-1">
            {([
              { id: '24h', label: '24H' },
              { id: '7d', label: '7D' },
              { id: '30d', label: '30D' },
            ] as const).map((t) => (
              <button
                key={t.id}
                onClick={() => onTimeframeChange(t.id)}
                className={`px-2.5 py-1 text-[10px] font-mono rounded font-bold transition-all duration-150 cursor-pointer ${
                  timeframe === t.id
                    ? 'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30'
                    : 'text-slate-400 hover:text-slate-200 hover:bg-slate-900'
                }`}
              >
                {t.label}
              </button>
            ))}
          </div>
        </div>

        {/* Narrative Text Container */}
        <div className="bg-slate-900/60 border border-slate-800 rounded-lg p-4 relative min-h-[160px] flex flex-col justify-between">
          <AnimatePresence mode="wait">
            {isGenerating ? (
              <div className="flex flex-col items-center justify-center py-10 space-y-3 flex-1" key="loading">
                <RefreshCw className="w-5 h-5 text-emerald-400 animate-spin" />
                <span className="text-[10px] font-mono text-slate-500 uppercase tracking-widest animate-pulse">
                  Synthesizing audit logs...
                </span>
              </div>
            ) : (
              <motion.div
                initial={{ opacity: 0, y: 3 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                transition={{ duration: 0.3 }}
                className="space-y-3 flex-1 flex flex-col justify-between"
                key="content"
              >
                {/* AI Text Block */}
                <p className="text-xs text-slate-300 leading-relaxed font-sans select-text">
                  {displayedText}
                </p>

                {/* Metadata Line */}
                <div className="pt-3 border-t border-slate-800/60 flex items-center justify-between text-[9px] font-mono text-slate-500">
                  <span className="flex items-center gap-1 uppercase">
                    <FileText className="w-3.5 h-3.5" /> Checked & Signed
                  </span>
                  <span>Oversight AI v1.4</span>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>

      {/* Advisory Warning */}
      <div className="mt-4 text-[10px] text-slate-500 bg-slate-950/40 p-2.5 rounded border border-slate-800/40 font-mono">
        <span className="text-amber-400 font-bold uppercase mr-1">Compliance Advisory:</span>
        This summary has been compiled directly from cryptographically signed local Firestore audit schemas, compliant with region security directives.
      </div>
    </div>
  );
};
